package context

import (
	"fmt"
	"strings"

	"github.com/MitAyush/chatapp/memory"
	"github.com/MitAyush/chatapp/models"
)

const (
	MaxContextTokens         = 5000
	RecentConversationTokens = 1500
	SummaryTokens            = 700
	MemoryTokens             = 500
)

// BuildContextV3 builds the messages that are sent to OpenRouter.
func BuildContextV3(req models.ChatRequest) []models.Message {
	state := memory.GetConversationState()

	systemPrompt := buildSystemPrompt(req, state.Summary)

	messages := []models.Message{
		{
			Role:    "system",
			Content: systemPrompt,
		},
	}

	recentMessages := selectRecentMessages(
		req.Messages,
		RecentConversationTokens,
	)

	messages = append(messages, recentMessages...)

	return messages
}

func buildSystemPrompt(
	req models.ChatRequest,
	rollingMemory string,
) string {
	var b strings.Builder

	// ============================================================
	// AI CHARACTER
	// ============================================================

	b.WriteString("[AI CHARACTER]\n")

	if strings.TrimSpace(req.CharacterDefinition) != "" {
		b.WriteString(strings.TrimSpace(req.CharacterDefinition))
	} else {
		b.WriteString("No AI character definition provided.")
	}

	b.WriteString("\n\n")

	// ============================================================
	// USER CHARACTER
	// ============================================================

	b.WriteString("[USER CHARACTER]\n")

	if strings.TrimSpace(req.UserCharacter) != "" {
		b.WriteString(strings.TrimSpace(req.UserCharacter))
	} else {
		b.WriteString("No user character information provided.")
	}

	b.WriteString("\n\n")

	// ============================================================
	// MEMORY
	// ============================================================

	b.WriteString("[MEMORY]\n")

	// Rolling memory generated by code.
	if strings.TrimSpace(rollingMemory) != "" {
		b.WriteString(strings.TrimSpace(rollingMemory))
		b.WriteString("\n")
	}

	// Memories currently stored in the request.
	for _, mem := range req.Memories {
		if !mem.Enabled {
			continue
		}
		content := strings.TrimSpace(mem.Content)

		if content == "" {
			continue
		}

		b.WriteString("- ")

		if mem.Importance > 0 {
			b.WriteString(fmt.Sprintf(
				"(importance %d) ",
				mem.Importance,
			))
		}

		b.WriteString(content)
		b.WriteString("\n")
	}
	b.WriteString("\n\n")

	// ============================================================
	// WHAT TO DO NEXT
	// ============================================================

	b.WriteString("[WHAT TO DO NEXT]\n")

	if strings.TrimSpace(req.NextInstructions) != "" {
		b.WriteString(strings.TrimSpace(req.NextInstructions))
	}

	b.WriteString("\n\n")

	// ============================================================
	// PRIORITY
	// ============================================================

	b.WriteString(`[INSTRUCTION PRIORITY]

WHAT TO DO NEXT has the highest priority.

Follow WHAT TO DO NEXT exactly.

If WHAT TO DO NEXT tells you to do something, do it.

If WHAT TO DO NEXT tells you not to do something, never do it.

Adapt immediately when WHAT TO DO NEXT changes.

AI CHARACTER defines who you are and how you normally behave.

USER CHARACTER describes the user.

MEMORY provides background information from previous conversation.

If information conflicts, follow the higher-priority instruction.

Do not allow MEMORY to override WHAT TO DO NEXT.

Do not allow USER CHARACTER or MEMORY to override WHAT TO DO NEXT.
`)

	return b.String()
}

// ================================================================
// MANUAL MEMORIES
// ================================================================

func selectEnabledMemories(memories []models.Memory) []models.Memory {
	result := make([]models.Memory, 0, len(memories))

	for _, mem := range memories {
		if !mem.Enabled {
			continue
		}

		if strings.TrimSpace(mem.Content) == "" {
			continue
		}

		result = append(result, mem)
	}

	return result
}

// ================================================================
// RECENT CONVERSATION
// ================================================================

func selectRecentMessages(
	messages []models.Message,
	budget int,
) []models.Message {
	if budget <= 0 || len(messages) == 0 {
		return nil
	}

	selected := make([]models.Message, 0)

	usedTokens := 0

	// Walk backwards so the newest messages are preferred.
	for i := len(messages) - 1; i >= 0; i-- {
		msg := messages[i]

		tokens := estimateTokens(msg.Content)

		if tokens <= 0 {
			tokens = 1
		}

		if usedTokens+tokens > budget {
			// If nothing has been selected yet, include the newest
			// message anyway rather than returning no conversation.
			if len(selected) == 0 {
				selected = append(selected, msg)
			}

			break
		}

		selected = append(selected, msg)
		usedTokens += tokens
	}

	// We selected backwards, so restore chronological order.
	for i, j := 0, len(selected)-1; i < j; i, j = i+1, j-1 {
		selected[i], selected[j] = selected[j], selected[i]
	}

	return selected
}

// ================================================================
// TOKEN ESTIMATION
// ================================================================

func estimateTokens(text string) int {
	text = strings.TrimSpace(text)

	if text == "" {
		return 0
	}

	// Simple approximation:
	// ~4 characters per token.
	return (len([]rune(text)) + 3) / 4
}
